### ISSUE TITLE
Can't change language

### ISSUE THREAD

**Issue by realriccio** [flathub/org.ppsspp.PPSSPP#37]
After downloading this on the Steam Deck via the built in flatpak store, i'm unable to change language to anything other than english. The list in the language setting only contains english. I tried disinstalling, removing all user data and reinstalling and the issue persists. Never had problems with non-flatpak versions on linux.

**Comment by catsout** [comment]
![image](https://user-images.githubusercontent.com/36527596/203994110-84e17214-5448-4730-b9be-6683fbd4d89a.png)

You need to change the `Language` in kde settings.  
And run `flatpak update`.

**Comment by catsout** [comment]
By the way, what's the language of your steam deck?

**Comment by realriccio** [comment]
The language of my steam deck is italian, but in desktop mode is english and it can't be changed in kde settings as "no additional languages are available". Isn't there a way to list all languages in ppsspp settings indipendently of system language like the non-flatpak version?

**Comment by JakeSmarter** [comment]
This has nothing to do with Flatpak nor Fluthub. It is a blunder by design from Valve. The reason why you cannot easily change locale settings in desktop mode on the Steam Deck is because all other (glibc) locales except for `en_US` have been excluded. See https://github.com/ValveSoftware/SteamOS/issues/794#issuecomment-1151520705 for details.

You can however manually install any missing (glibc) locales from the official Arch Linux repo. But, it is rather complicated for inexperienced users because the system partition on the Steam Deck is write protected and the locales may vanish on a regular system update from Valve or block an update from getting installed.

> The list in the language setting only contains english.

This is also by design by Flatpak because by default you only get localization data per app for locales you have configured in your user profile and any additional locales configured system wide. So, it is not a bug, it is a feature of Flatpak. Now, although you cannot configure system locales on the Steam Deck, you can configure Flatpak locales. See [Flatpak’s manual on how to configure locales using `flatpak config`](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-config).

In your case, if you want to have Italian installed in addition to `en_US` (because for Flatpak `en_US` is the configured system locale) with every Flatpak app you would issue this command:
```
flatpak config --set extra-languages it
```
On the Steam Deck, you would probably want to have your additional Flatpak locales configured rather system wide than just per user:
```
flatpak config --system --set extra-languages it
```
